# How to Handle Exceptions

<!-- TOC -->

- [1. throw and throws](#1-throw-and-throws)
- [2. try-catch Blocks](#2-try-catch-blocks)
- [3. finally](#3-finally)
  - [3.1. finally Blocks](#31-finally-blocks)
  - [3.2. Java 7: try-with-resources Statement](#32-java-7-try-with-resources-statement)
- [4. catch](#4-catch)
  - [4.1. Multiple catch Blocks](#41-multiple-catch-blocks)
  - [4.2. Java 7: Union catch Blocks](#42-java-7-union-catch-blocks)
- [5. What if I really don't care about the exceptions](#5-what-if-i-really-dont-care-about-the-exceptions)

<!-- /TOC -->

Five keywords are used in exception handling: `try`, `catch`, `finally`, `throws` and `throw` (take note that there is a difference between `throw` and `throws`).

## 1. throw and throws

The easiest way to take care of a compiler error when dealing with a checked exception is to simply throw it.

```java
public File getFile(String url) throws FileNotFoundException {
    // some code
    throw new FileNotFoundException();
}
```

We are required to mark our method signature with a `throws` clause. A method can add as many exceptions as needed in its `throws` clause, and can throw them later on in the code, but doesn't have to. This method doesn't require a return statement, even though it defines a return type. This is because it throws an exception by default, which ends the flow of the method abruptly. The return statement, therefore, would be unreachable and cause a compilation error.

Keep in mind that anyone who calls this method also needs to follow the **handle-or-declare** rule.

When throwing an exception, we can either **throw a new exception**, like in the preceding example, or a **caught exception**.

## 2. try-catch Blocks

A more common approach would be to use a `try-catch` block to catch and handle the arising exception:

```java
public String readFirstLine(String url) throws FileNotFoundException {
    try {
        Scanner scanner = new Scanner(new File(url));
        return scanner.nextLine();
    } catch(FileNotFoundException ex) {
        throw ex;
    }
}
```

In this example, we "marked" a risky segment of code by encasing it within a `try` block. This tells the compiler that we're aware of a potential exception and that we're intending to handle it if it arises.

This code tries to read the contents of the file, and if the file is not found, the `FileNotFoundException` is caught and rethrown.

Running this piece of code without a valid URL will result in a thrown exception:

```txt
Exception in thread "main" java.io.FileNotFoundException: some_file (The system cannot find the file specified) <-- some_file doesn't exist
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.util.Scanner.<init>(Scanner.java:611)
    at Exceptions.ExceptionHandling.readFirstLine(ExceptionHandling.java:15) <-- Exception arises on the the     readFirstLine() method, on line 15
    at Exceptions.ExceptionHandling.main(ExceptionHandling.java:10) <-- readFirstLine() is called by main() on  line 10
...
```

Alternatively, we can try to recover from this condition instead of rethrowing:

```java
public static String readFirstLine(String url) {
    try {
        Scanner scanner = new Scanner(new File(url));
        return scanner.nextLine();
    } catch(FileNotFoundException ex) {
        System.out.println("File not found.");
        return null;
    }
}
```

Running this piece of code without a valid URL will result in:

```txt
File not found.
```

## 3. finally

### 3.1. finally Blocks

Introducing a new kind of block, the `finally` block executes regardless of what happens in the `try` block. Even if it ends abruptly by throwing an exception, the `finally` block will execute.

This was **often used to close the resources** that were opened in the `try` block since an arising exception would skip the code closing them:

```java
public String readFirstLine(String path) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader(path));
    try {
        return br.readLine();
    } finally {
        if(br != null) br.close();
    }
}
```

However, this approach has been frowned upon after the release of Java 7, which introduced a better and cleaner way to close resources, and is currently seen as bad practice.

### 3.2. Java 7: try-with-resources Statement

The previously complex and verbose block can be substituted with:

```java
static String readFirstLineFromFile(String path) throws IOException {
    try(BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```

It's much cleaner and it's obviously simplified by including the declaration within the parentheses of the `try` block.

Additionally, you can include multiple resources in this block, one after another:

```java
static String multipleResources(String path) throws IOException {
    try(BufferedReader br = new BufferedReader(new FileReader(path));
        BufferedWriter writer = new BufferedWriter(path, charset)) {
        // some code
    }
}
```

This way, you don't have to concern yourself with closing the resources yourself, as the **try-with-resources** block ensures that the resources will be closed upon the end of the statement.

## 4. catch

### 4.1. Multiple catch Blocks

When the code we're writing can throw more than one exception, we can employ several catch blocks to handle them individually:

```java
public void parseFile(String filePath) {
    try {
        // some code
    } catch (IOException ex) {
        // handle
    } catch (NumberFormatException ex) {
        // handle
    }
}
```

When the `try` block incurs an exception, the JVM checks whether the first caught exception is an appropriate one, and if not, goes on until it finds one.

Note: Catching a generic exception will catch all of its subclasses so it's not required to catch them separately.

Catching a `FileNotFoundException` isn't necessary in this example, because it extends from `IOException`, but if the need arises, we can catch it before the `IOException`:

```java
public void parseFile(String filePath) {
    try {
        // some code 
    } catch(FileNotFoundException ex) {
        // handle
    } catch (IOException ex) {
        // handle
    } catch (NumberFormatException ex) {
        // handle
    }
}
```

This way, we can handle the more specific exception in a different manner than a more generic one.

Note: **When catching multiple exceptions, the Java compiler requires us to place the more specific ones before the more general ones, otherwise they would be unreachable and would result in a compiler error**.

### 4.2. Java 7: Union catch Blocks

To reduce boilerplate code, Java 7 also introduced union catch blocks. They allow us to treat multiple exceptions in the same manner and handle their exceptions in a single block:

```java
public void parseFile(String filePath) {
    try {
        // some code
    } catch (IOException | NumberFormatException ex) {
        // handle
    }
}
```

## 5. What if I really don't care about the exceptions

Certainly not advisable other than writing toy programs. But to bypass the compilation error messages triggered by methods declaring unchecked exceptions, you could declare "throws Exception" in your `main()` (and other methods), as follows:

```java
public static void main(String[] args) throws Exception {  // throws all subclass of Exception to JRE
   Scanner in = new Scanner(new File("test.in"));   // declares "throws FileNotFoundException"
   ......
   // other exceptions
}
```
